[tools]
direnv = "latest"
watchexec = "latest"

[env]
PLATFORM = "linux/amd64"

[tasks."build"]
description = "build library"
run = "cargo build"

[tasks."build:watch"]
description = "watch library"
run = "cargo watch -x 'test'"

[tasks."lint"]
description = "lint rust"
run = """
cd $root
cargo clippy --all --
"""

[tasks."fmt"]
description = "format rust"
run = """
cd $root
cargo fmt --all
"""

[tasks."test"]
description = "run tests"
run = """
cd $root
cargo test
"""

[tasks."audit"]
description = "cargo deny"
run = """
cd $root
cargo deny check
"""

[tasks."all"]
depends = ["lint", "fmt", "test", "audit"]
