name: linter

on:
  pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Run Rust code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup mise
        uses: jdx/mise-action@v2
        with:
          experimental: true
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt
      - name: linting with clippy
        run: mise run lint
